# Generated by Django 2.0 on 2021-02-08 08:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_readnum'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='readnum',
            name='blog',
        ),
        migrations.DeleteModel(
            name='ReadNum',
        ),
    ]
